### PR TITLE
Fix typo in gcc realtime attribute

### PR DESCRIPTION
**Pull request by cjappl**

### CODE REVIEW

**Comment by davidtrevelyan** [comment]
@cjappl Looks like this has got the realtime bypass stuff included in the changes too - was that intentional?

**Comment by cjappl** [comment]
@davidtrevelyan whoops! 😅 

Fixed!!

**Comment by cjappl** [comment]
Also, what do these attributes mean? Can I annotate with just [[realtime]]?

I'm not sure what the difference between the different "categories" of these spellings are:

```
  let Spellings = [CXX11<"clang", "realtime">, 
                   C23<"clang", "realtime">,
                   GCC<"realtime">];
```

aka CXX11, C23 and GCC

**Comment by davidtrevelyan** [comment]
Good question on the spellings - I can't remember. I'll have a look tomorrow!

**Pull request merged**
